server:
  tomcat:
    max-connections: 200
    threads:
      max: 200
      min-spare: 10
#    connection-timeout: 29000
#  servlet:
#    session:
#      timeout: 29s
  session:
    timeout: 29
spring:
    profiles:
      active: postgre # mysql|postgre
    mvc:
      async:
        request-timeout: 20000
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  configuration: map-underscore-to-camel-case=true
